# Generated by Django 4.1.5 on 2023-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='furniture',
            name='category',
            field=models.ManyToManyField(to='partshop.category'),
        ),
    ]
