# Generated by Django 4.1.5 on 2023-02-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partshop', '0002_rename_categorie_category_furniture_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='category',
        ),
        migrations.AddField(
            model_name='furniture',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='partshop.category', verbose_name='category'),
        ),
    ]
