# Generated by Django 4.1.5 on 2023-01-12 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description_shorted', models.CharField(max_length=200)),
                ('description_full', models.TextField()),
                ('main_photo', models.URLField(max_length=500)),
                ('thumbnail_photo', models.URLField(max_length=500)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('colours', models.ManyToManyField(to='utils.palette')),
                ('gallery', models.ManyToManyField(to='utils.photo')),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.handle')),
                ('main_colour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='utils.palette', verbose_name='main_color')),
                ('main_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='utils.material', verbose_name='main_material')),
                ('main_style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style', to='utils.style', verbose_name='main_style')),
                ('materials', models.ManyToManyField(to='utils.material')),
                ('styles', models.ManyToManyField(to='utils.style')),
            ],
        ),
    ]
